# Copy to config.yaml and edit your VOYAGE_API_KEY.
index_dir: ./index
bm25_index_path: ./index_bm25
data_path: ./data/sample_docs.jsonl
embedding:
  provider: voyage
  model: voyage-2        # supported model
  dim: 1024              # set to your model's embedding dimension
  batch_size: 16
  api_key_env: VOYAGE_API_KEY
faiss:
  type: ivf_pq           # [hnsw, flat, ivf_pq]
  nlist: 4096            # coarse centroids (use lower for small datasets)
  m: 32                  # PQ subvectors
  nprobe: 16             # query-time probes
retrieval:
  top_m: 200             # candidates to send to reranker
  top_k: 20              # final chunks returned to generator
reranker:
  type: colbert          # [colbert, crossencoder]
  colbert_model: colbert-ir/colbertv2.0
  max_query_len: 64
  max_doc_len: 180
generator:
  max_context_tokens: 3000
  # (left for your LLM of choice)
