# Copy to config.yaml and edit your VOYAGE_API_KEY.
index_dir: ./index
bm25_index_path: ./index_bm25
data_path: ./data/sample_docs.jsonl
embedding:
  provider: voyage
  model: voyage-2        # supported model per API (previously voyage-context-3)
  dim: 1024              # adjust to your voyage model's output dim
  batch_size: 16
  api_key_env: VOYAGE_API_KEY
faiss:
  type: ivf_pq           # [hnsw, flat, ivf_pq]
  nlist: 4096            # coarse centroids
  m: 32                  # PQ subvectors
  nprobe: 16             # query-time probes
retrieval:
  top_m: 200             # candidates to send to reranker
  top_k: 20              # final chunks returned to generator
reranker:
  enabled: true          # Must be true to use reranker
  type: colbert          # [colbert, crossencoder]
  colbert_model: colbert-ir/colbertv2.0
  reranker_k: 10         # Top K results after reranking
  max_query_len: 64
  max_doc_len: 180
  device: cpu            # or cuda if available
generator:
  max_context_tokens: 3000
  # (left for your LLM of choice)
