# Copy to config.yaml and edit your VOYAGE_API_KEY.
index_dir: ./index
data_path: ./data/sample_docs.jsonl
device: cpu
embedding:
  provider: voyage
  model: voyage-2 #voyage-context-3        # change if you use a different model
  dim: 1024                      # adjust to your voyage model's output dim
  batch_size: 16
  api_key_env: VOYAGE_API_KEY
faiss:
  type: ivf_pq                   # [hnsw, flat, ivf_pq]
  nlist: 64                      # coarse centroids (lowered for local testing/small samples)
  m: 32                          # PQ subvectors
  nprobe: 16                     # query-time probes
retrieval:
  top_m: 200                     # candidates to send to reranker
  top_k: 20                      # final chunks returned to generator
reranker:
  enabled: true
  colbert_model: "colbert-ir/colbertv2.0"
  reranker_k: 10
  device: null # auto-detect
generator:
  max_context_tokens: 3000
  # (left for your LLM of choice)

# Root directory for the dense FAISS index and metadata.
index_path: "./index"
# Directory for the sparse BM25 index.
bm25_index_path: "./index_bm25"

# --- Retrieval/Reranking Parameters ---

# Number of candidates to retrieve from ANN index (dense) and BM25 (sparse).
