name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install project (dev)
        run: pip install -e '.[dev]'
      - name: Lint
        run: |
          ruff check .
          ruff format --check .
      - name: Type check
        run: mypy .
      - name: Tests
        env:
          VOYAGE_API_KEY: 'placeholder'
        run: pytest -q

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t rag-voyage-demo:ci .
