name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install project (dev)
        run: pip install -e '.[dev]'
      - name: Lint
        run: |
          ruff check --version
          ruff format --version
          ruff check .
          ruff format --check .
      - name: Type check
        run: mypy .
      - name: Tests
        env:
          VOYAGE_API_KEY: 'placeholder'
        run: pytest -q

  docker:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push Docker image
        env:
          IMAGE: ghcr.io/${{ github.repository_owner }}/rag-voyage-demo
          SHA: ${{ github.sha }}
        run: |
          docker build -t "$IMAGE:latest" -t "$IMAGE:$SHA" .
          docker push "$IMAGE:latest"
          docker push "$IMAGE:$SHA"
